int add(int x, int y);
int pole(int b1,int b2,int b3);
int maks(int x, int y, int z);
long int suma1(int n);
long int suma2(int minimum, int maximum);
int wartoscMaks(int granica);
int minis(int t[],int n);
int liczba_wystapien(char *l, char znak, int *wystapienie);
void wzor_kwadratowy(int a, int b, int c);
void dwojkowa_reprezentacja(int n);
int ktoraCwiartka(float x, float y);
float suma3(float x, int n);
float suma4(float x, int n);
float suma5(float x, float epsilon);
void czy_pierwsza(int liczba);
void wypisz_tab(int w,float t[w]);
int zlicz(int t[], int n);
void odwroc(char str[]);
int liczba_slow(char *lancuch);

