int* z8_1(int n);
char* z8_3(char *s1, char *s2);
int* z8_4(int *t, int n, int m);
int* z8_4v2(int *t, int n, int m);
int* z8_5(int **t,int n, int m);
int* macierz(int n, int m);
void wypisz1(int *t, int n);
void wypisz_macierz(int **t,int n, int m);
int** z8_6(int *tab,int d, int n, int m);
int* z8_7(int *t,int idx0, int idx1);
int* z8_8(int *t, int n, int a, int b,int* il);
int* z8_9(int *tab, int dl, int idx, int wartosc);
